services:
  osrm-router:
    image: osrm/osrm-backend:latest
    container_name: osrm-router
    ports:
      - "5000:5000"
    volumes:
      - ./maps:/data
    command: >
      sh -c "if [ ! -f /data/combined.osrm ]; then echo 'Starting map processing...'; osrm-extract -p /opt/car.lua /data/combined.osm.pbf && osrm-partition /data/combined.osrm && osrm-customize /data/combined.osrm; else echo 'Using cached map data.'; fi; osrm-routed --algorithm mld /data/combined.osrm"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
  pg_taxi:
    image: "postgis/postgis:15-3.4"
    container_name: pg_taxi
    restart: always
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=${DB_USER}"
      - "TZ=UTC"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network
    ports:
      - ${DB_PORT}:5432
  redis_taxi:
    image: redis:7-alpine
    container_name: redis_taxi
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_redis:/redis
    networks:
      - app_network
    ports:
      - ${REDIS_PORT}:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: "redis_taxi"
      REDIS_HOST: redis_taxi
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASS}
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - app_network

volumes:
  pg_data:
  pg_redis:

networks:
  app_network:
    driver: bridge