SERVER_PORT: 8080
SERVER_HOST: localhost
DB_PASS: ${DB_PASS}
DB_USER: ${DB_USER}
DB_NAME: ${DB_NAME}
DB_PORT: ${DB_PORT}
DB_HOST: ${DB_HOST}
MAIL_HOST: ${MAIL_HOST}
MAIL_PORT: ${MAIL_PORT}
MAIL_USERNAME: ${MAIL_USERNAME}
MAIL_PASSWORD: ${MAIL_PASSWORD}
WEBSOCKET_PORTS: ${WEBSOCKET_PORTS}
REDIS_HOST: ${REDIS_HOST}
REDIS_PASS: ${REDIS_PASS}
REDIS_DB: ${REDIS_DB}
REDIS_PORT: ${REDIS_PORT}