logging:
  file:
    name: ./logs/application.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} %msg%n'
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    redis.clients.jedis: DEBUG

spring:
  springdoc:
    webjars:
      prefix: ""
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: your-taxi
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/master.yml
  data:
    redis:
      host: ${REDIS_HOST}
      database: ${REDIS_DB}
      password: ${REDIS_PASS}
      port: ${REDIS_PORT}
server:
  port: ${SERVER_PORT}
  host: ${SERVER_HOST}
jwt:
  access:
    secretKey: ${ACCESS_SECRET_KEY}
    ttlMinutes: ${ACCESS_TTL_MINUTES}
  refresh:
    secretKey: ${REFRESH_SECRET_KEY}
    ttlMinutes: ${REFRESH_TTL_MINUTES}

websocket:
  ports: ${WEBSOCKET_PORTS}
frontend:
  url: ${FRONTEND_URL}
services:
  osrm:
    host: ${OSRM_HOST}

