spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always
  springdoc:
    webjars:
      prefix: ""
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: your-taxi
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  data:
    redis:
      host: ${REDIS_HOST}
      database: ${REDIS_DB}
      password: ${REDIS_PASS}
      port: ${REDIS_PORT}
server:
  port: ${SERVER_PORT}
  host: ${SERVER_HOST}
jwt:
  access:
    secretKey: ${ACCESS_SECRET_KEY}
    ttlMinutes: ${ACCESS_TTL_MINUTES}
  refresh:
    secretKey: ${REFRESH_SECRET_KEY}
    ttlMinutes: ${REFRESH_TTL_MINUTES}

websocket:
  ports: ${WEBSOCKET_PORTS}
frontend:
  url: ${FRONTEND_URL}
backend:
  url: ${BACKEND_URL}
services:
  osrm:
    host: ${OSRM_HOST}
rate-limit:
  login:
    max-attempts: 5
    window-minutes: 5
    block-duration-minutes: 30

  registration:
    max-attempts: 3
    window-minutes: 15

  api:
    max-attempts: 100
    window-minutes: 1
