name: Java CI/CD with Maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B package --file pom.xml
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Cd to folder
        run: cd /home/runner/projects/your_taxi
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Docker build
        run: docker compose -f compose.yaml up -d --build
        env:
          EXPOSE_SERVER_PORT: ${{ secrets.EXPOSE_SERVER_PORT }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          WEBSOCKET_PORTS: ${{ secrets.WEBSOCKET_PORTS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_DB: ${{ secrets.REDIS_DB }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
          REFRESH_TTL_MINUTES: ${{ secrets.REFRESH_TTL_MINUTES }}
          ACCESS_TTL_MINUTES: ${{ secrets.ACCESS_TTL_MINUTES }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          OSRM_HOST: ${{ secrets.OSRM_HOST }}


